[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''(
    \.git|
    \.venv|
    venv|
    env|
    stockpulse-env|
    envs|
    node_modules|
    build|
    dist|
    \.vscode|
    \.idea|
    \.tox|
    \.eggs
)'''
